# Docker — ROOTLESS, user-level daemon after the secrets.server removal.
#
# The daemon is a systemd --user unit generated by nixos (dockerd-rootless,
# ConditionUser=!root, socket at $XDG_RUNTIME_DIR/docker.sock). Its full
# lifecycle belongs to the services hub plugin: toggle via the panel, auto-
# start via the plugin's docker_auto_start one-shot at shell boot — NOT at
# login (wantedBy is forced empty below; the nixpkgs unit auto-starts at
# default.target otherwise).
#
# Consequences of rootless:
#   * daemon + images/volumes run as the user in ~/.local/share/docker
#     (the old root daemon's /var/lib/docker data is NOT carried over),
#   * DOCKER_HOST points at the user socket (envfs extraInit for shells;
#     the sonarqube wrapper targets the same socket),
#   * works with k3d/kubectl; port bindings require >1024 (fine here),
#   * SonarQube (home-modules/sonarqube.nix) runs on this daemon.
{ pkgs, lib, ... }:
{
  virtualisation = {
    docker.rootless = {
      enable = true;
      setSocketVariable = true;
      # rootlesskit (user-ns bootstrapper) + slirp4netns (user-land networking)
      # are required at daemon runtime; fuse-overlayfs gives the daemon a fast
      # storage driver fallback.
      extraPackages = with pkgs; [
        rootlesskit
        slirp4netns
        fuse-overlayfs
      ];
    };

    containers = {
      enable = true;
      registries.settings.registries.search.registries = [
        "docker.io"
        "registry.fedoraproject.org"
      ];
    };
  };

  # nixpkgs' rootless unit auto-starts at login (wantedBy = default.target);
  # the plugin owns the lifecycle instead.
  systemd.user.services.docker.wantedBy = lib.mkForce [ ];

  # Subordinate uid/gid mapping — required for dockerd-rootless user namespace
  # (newuidmap/newgidmap reject the daemon without it).
  users.users.geryruslandi.subUidRanges = [
    {
      startUid = 100000;
      count = 65536;
    }
  ];
  users.users.geryruslandi.subGidRanges = [
    {
      startGid = 100000;
      count = 65536;
    }
  ];

  environment.systemPackages = with pkgs; [
    docker-compose

    kubectl
    k3d
    just
  ];
}
